# +---------------------------------------------------+
# |                                                   |
# |           CustomKits Minecraft Plugin             |
# |                Konfigurationsfil                  |
# |                 Author: Itz_Tix                   |
# +---------------------------------------------------+


# ==== General Options ====

language: "en" # Two options either "da" for danish or as default "en" for english

update-message: true
# Whether to send a message when a new update is available.
# If this is set to true, it will send an operator a message when joining the server.
# If set to false, you can check for the newest version via /ckit version





